baseURL = "https://xiayuguo.com/"
languageCode = "en-us"
title = "随笔"
theme = "slim"

# [permalinks]
#   posts = "/:year/:month/:title/"

[params]
  Subtitle = "Stay hungry. Stay foolish."
  GithubID = "xiayuguo"
  # TwitterID = "Your Twitter ID"
  # AnalyticsID = "Your Google Analytics tracking code"
  DisqusShortname = "yuguo"
  Summary = false  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  # FooterMsg = "Copyright@<a href='http://localhost:1313/about'>Hugoxia</a> 2018. Powered by <a href='https://gohugo.io/'>Hugo</a>. This theme—Slim—is open sourced on <a href='https://github.com/zhe/hugo-theme-slim'>Github</a>."
  FooterMsg = "Copyright@<a href='https://xiayuguo.com/about'>Yuguo</a> 2019. Powered by <a href='https://gohugo.io/'>Hugo</a>. This theme—Slim—is open sourced on <a href='https://github.com/zhe/hugo-theme-slim'>Github</a>."
